services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres
    command: start-dev --import-realm
  postgres:
    image: postgres:14.7-alpine
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    volumes:
      - postgres:/var/lib/postgresql/data
  discoveryservice:
    image: hiroshinobuoka/discovery-service
    ports:
      - 8761:8761
    depends_on:
      - postgres
      - keycloak
  configservice:
    image: hiroshinobuoka/config-service
    depends_on:
      - discoveryservice
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    # overriding defaultZone from localhost -> Docker-managed host (i.e. "discoveryservice")
    environment:
      - eureka.client.service-url.defaultZone=http://discoveryservice:8761/eureka/
  adminservice:
    image: hiroshinobuoka/admin-service
    depends_on:
      - discoveryservice
      - configservice
      - usersservice
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    # overriding oauth2 URI from localhost -> Docker-managed host (i.e. "keycloak")
    environment:
      - eureka.client.service-url.defaultZone=http://discoveryservice:8761/eureka/
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/movierecs-realm/protocol/openid-connect/certs
      # for resttemplate call when checking if email exists
      - keycloak.server.host=http://172.17.0.1:8080
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  usersservice:
    image: hiroshinobuoka/users-service
    depends_on:
      - discoveryservice
      - configservice
      - mysqlservice
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - eureka.client.service-url.defaultZone=http://discoveryservice:8761/eureka/
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/movierecs-realm/protocol/openid-connect/certs
      - spring.datasource.url=jdbc:mysql://mysqlservice:3306/movierecs
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  mysqlservice:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=movierecs
      - MYSQL_USER=movierecs-admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql:/var/lib/movierecs-volumes/mysql-data
  gatewayresourceservice:
    image: hiroshinobuoka/gateway-resource-service
    ports:
      - 8087:8087
    depends_on:
      - discoveryservice
      - configservice
      - usersservice
      - adminservice
    environment:
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/movierecs-realm/protocol/openid-connect/certs
      - eureka.client.service-url.defaultZone=http://discoveryservice:8761/eureka/
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  zipkinstorage:
    image: openzipkin/zipkin-mysql
    container_name: zipkinstorage
    # Uncomment to expose the storage port for testing
    # ports:
    #   - 3308:3306

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkinstorage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    depends_on:
      - zipkinstorage
      - gatewayresourceservice
      - usersservice
      - adminservice
volumes:
  postgres:
    name: "keycloak-data"
  mysql:
    name: "users-data"
