filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/containers/*/*-json.log
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

output.console:
  enabled: false
  pretty: true

