server:
  port: 8086

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/realms/movierecs-realm/protocol/openid-connect/certs